version: '3'
networks:
  tulo_bridge:
    external: true
volumes:
  bundle:
services:
  redis:
    image: redis:4.0-alpine
    ports:
      - "6377:6379"
    volumes:
      - ./tmp/data/redis:/data:cached
  app:
    build:
      context: .
    stdin_open: true
    tty: true
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - bundle:/usr/local/bundle
      - .:/usr/src/app:delegated
    ports:
      - "3000:3000"
    networks:
      - tulo_bridge
      - default
    depends_on:
      - redis
