departments:
  host: <%= ENV.fetch('DEPARTMENTS_HOST') { 'tulo_departments_app_1:50051' } %>

employees:
  host: <%= ENV.fetch('EMPLOYEES_HOST') { 'tulo_employees_app_1:50051' } %>

common:
  host: <%= ENV.fetch('COMMON_HOST') { 'tulo_common_app_1:50051' } %>

documents:
  host: <%= ENV.fetch('DOCUMENTS_HOST') { 'tulo_documents_app_1:50051' } %>

tasks:
  host: <%= ENV.fetch('TASKS_HOST') { 'tulo_tasks_app_1:50051' } %>

env:
  name: <%= ENV['ENV_NAME'] %>

encrypted_password:
  pepper: "0c926a9f54004241775fbec5df837607f04a06f096c76a24efe37a70992cbfbf"
  stretches: 12
